name: Call MakeOSCAL and Upload Actions

on:
  push:
    branches:
      - master2 # Replace 'main' with your default branch name if different

jobs:
  call_routes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: |
        sudo apt-get install jq

    - name: Call MakeOSCAL action on Flask app
      run: |
        response=$(curl -s -X GET "http://pipeline.fotonotes.net/makeoscal")
        echo "Response: $response"
        cleaned_response=$(echo "$response" | tr -d '\000-\037')
        status=$(echo "$cleaned_response" | jq -r '.status')
        if [ "$status" != "OK" ]; then
          echo "MakeOSCAL action failed"
          exit 1
        fi

    - name: Call Upload action on Flask app
      run: |
        response=$(curl -s -X GET "http://pipeline.fotonotes.net/upload")
        echo "Response: $response"
        cleaned_response=$(echo "$response" | tr -d '\000-\037')
        status=$(echo "$cleaned_response" | jq -r '.status')
        if [ "$status" != "OK" ]; then
          echo "Upload action failed"
          exit 1
        fi
