name: Call MakeOSCAL and Upload Actions

on:
  push:
    branches:
      - master # Replace 'main' with your default branch name if different

jobs:
  call_routes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: |
        sudo apt-get install jq

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install rtyaml natsort requests structlog

    - name: Create settings.py in the scripts directory
      run: |
        echo "INPUTDIR = '../freedonia-compliance-2/components'" >> ./scripts/settings.py
        echo "OUTPUTDIR = '../freedonia-compliance-2/output/oscal'" >> ./scripts/settings.py

    - name: Run myscript.py from the scripts directory
      run: python ./scripts/make_oscal.py

#    - name: Call MakeOSCAL action on Flask app
#      run: |
#        response=$(curl -s -X GET "http://pipeline.fotonotes.net/makeoscal")
#        echo "Response: $response"
#        cleaned_response=$(echo "$response" | tr -d '\000-\037')
#        status=$(echo "$cleaned_response" | jq -r '.status')
#        if [ "$status" != "OK" ]; then
#          echo "MakeOSCAL action failed"
#          exit 1
#        fi
#
#    - name: Call Upload action on Flask app
#      run: |
#        response=$(curl -s -X GET "http://pipeline.fotonotes.net/upload")
#        echo "Response: $response"
#        cleaned_response=$(echo "$response" | tr -d '\000-\037')
#        status=$(echo "$cleaned_response" | jq -r '.status')
#        if [ "$status" != "OK" ]; then
#          echo "Upload action failed"
#          exit 1
        fi
