name: ETL Components

on:
  push:
    branches:
      - master # Replace 'main' with your default branch name if different

jobs:
  call_routes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: |
        sudo apt-get install jq

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install rtyaml natsort requests structlog

    - name: Create settings.py in the scripts directory
      run: |
        echo "INPUTDIR = '../freedonia-compliance-2/components'" >> ./scripts/settings.py
        echo "OUTPUTDIR = '../freedonia-compliance-2/output/oscal'" >> ./scripts/settings.py

    - name: Run myscript.py from the scripts directory
      run: python ./scripts/make_oscal.py

    - name: Clone private repository and switch to specific branch
      env:
        REGSCALE_CLI_PAT: ${{ secrets.REGSCALE_CLI_PAT }}
      run: |
        git clone https://x-access-token:${REGSCALE_CLI_PAT}@github.com/RegScale/regscale-cli.git
        cd regscale-cli
        git checkout ge/oscal_component_fixes
        pip install -r requirements.txt
        python regscale.py about
        
